"""initial_schema_baseline

Revision ID: 7b320d8bde6a
Revises: 
Create Date: 2026-04-22 21:07:28.025157
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7b320d8bde6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('mounted_folders',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.drop_column('folder_slug')
        batch_op.drop_column('folder_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('folder_slug', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('mounted_folders',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###
